puts "Convenções"
puts "indentação de 2 espaços"
puts "Variáveis sempre escritas em snake_case"
puts "Constantes sempre em UPPERCASE"
puts "Classes e métodos sempre em CamelCase com a primeira letra maiúscula"
puts "Ponto e vírgula não e necessário somente se for utilizar diversas sentenças na mesma linha Ex: a = 1; b = 2"
